#!/usr/bin/env bash

# Prepare the environment
## reference: https://vsupalov.com/docker-arg-env-variable-guide/
## our .env file is used BOTH for substitutions within docker-compose.yml AND to define ENV entries in the containers

# Reset the environment file
echo "# This file is generated by create.sh" > .env
echo "# This file is generated by create.sh" > env_file

# Configure the environment
## Update the contents of the .env (for docker-compose) and/or env_file (for the container) as needed
echo DEBUG=1 >> .env
echo BUILD_PYTHON_VERSION=$(cat ./.python-version) >> .env
echo BUILD_USERNAME=foo >> .env
echo BUILD_UID=$(id -u) >> .env
echo BUILD_GID=$(id -g) >> .env

# Build the container
docker-compose  --project-name python-notes build
